<div class="content">
    <h2>BlackBox-Settings</h2>

    <h3>Deine Account-Einstellungen</h3>
    <?php
    $usersettings = $this->usersettings;
    ?>
    <div class="row settings">
        <div class="col-12 col-sm-12 col-lg-6 user-save-data">
            <div class="row">
                <div class="col-12 col-sm-12 headline">
                    <h4>Speichereinstellungen</h4>
                </div>
                <div class="col-12 col-sm-12 col-md-4  settings-attribute"><p>In der Dropbox speichern?</p></div>
                <div class="col-12 col-sm-12 col-md-8  settings-value">
                    <p><?php echo ($usersettings->getSaveCloud()) ? "Ja" : "Nein"; ?><p></div>

                <?php
                if ($usersettings->getSaveCloud()) {
                    ?>
                    <div class="col-12 col-sm-12 col-md-4 settings-attribute"><p>Dropbox Speicherordner</p></div>
                    <div class="col-12 col-sm-12 col-md-8 settings-value">
                        <p><?php echo $usersettings->getSaveLocationCloud(); ?><p></div>
                    <div class="col-12 col-sm-12 col-md-4 settings-attribute"><p>Dropbox Username</p></div>
                    <div class="col-12 col-sm-12 col-md-8 settings-value">
                        <p><?php echo $usersettings->getUsernameCloud(); ?><p></div>
                    <div class="col-12 col-sm-12 col-md-4 settings-attribute"><p>Dropbox Password</p></div>
                    <div class="col-12 col-sm-12 col-md-8 settings-value">
                        <p>***
                        <p></div>
                    <?php
                }
                ?>

                <div class="col-12 col-sm-12 col-md-4  settings-attribute"><p>maximale Datei-Upload-Grenze</p></div>
                <div class="col-12 col-sm-12 col-md-8  settings-value">
                    <p><?php echo ($usersettings->getMaxFileUpload() >= 1000) ? (($usersettings->getMaxFileUpload() / 1000) . " GB") : ($usersettings->getMaxFileUpload() . "MB"); ?>
                    <p></div>
                <div class="col-12 col-sm-12 col-md-4  settings-attribute"><p>lokale Gesamtspeichergröße</p></div>
                <div class="col-12 col-sm-12 col-md-8  settings-value">
                    <p><?php echo ($usersettings->getMaxStorage() >= 1000) ? (($usersettings->getMaxStorage() / 1000) . " GB") : ($usersettings->getMaxStorage() . "MB"); ?>
                    <p></div>
                <div class="col-12 col-sm-12 col-md-4  settings-attribute"><p>erlaubte Dateiformate</p></div>
                <div class="col-12 col-sm-12 col-md-8  settings-value">
                    <?php
                    $fileformats = $usersettings->getAllowedFileFormats();
                    echo "<ul class='fileformat'>";
                    foreach ($fileformats as $fileformat) {
                        echo "<li>" . $fileformat . "</li>";
                    }
                    echo "</ul>";
                    ?>
                </div>
                <div class="col-12 col-sm-12 edit">
                    <a href="<?php echo $this->url(array('controller' => 'user-settings', 'action' => 'edit')) ?>" class="button">Bearbeiten</a>
                </div>
            </div>
        </div>
    </div>
</div>