<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width initial-scale=1.0"/>

    <title>Blackbox // Uplaod.Taggen.Finden.</title>

    <meta name="description" content="Ein Speicherort, der es ermöglicht anhand so genannter Tags (Stichwörter) Dateien zu speichern und wieder zu finden."/>
    <meta name="author" content="Christoph Stockinger"/>
    <meta name="publisher" content="Christoph Stockinger"/>
    <meta name="copyright" content="&copy; Christoph Stockinger"/>
    <meta name="version" content="1.0"/>


    <!--// Favicon //-->
    <link rel="apple-touch-icon" sizes="57x57" href="/images/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/images/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/images/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/images/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/images/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/images/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/images/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/images/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/images/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="/images/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/images/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon/favicon-16x16.png">
    <link rel="manifest" href="/images/favicon/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/images/favicon/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <link rel="shortcut icon" type="image/vnd.microsoft.icon" href="/favicon.ico">

    <!--// CSS //-->
    <!--// CSS Bootstrap Grid //-->
    <link href="/css/bootstrap.min.css" rel="stylesheet" type="text/css" media="all">
    <!--// CSS CS Reset //-->
    <link href="/css/cs-reset.css" rel="stylesheet" type="text/css" media="all">
    <!--// CSS Main //-->
    <link href="/css/main.css" rel="stylesheet" type="text/css" media="all">

</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bb-blackbox-bg">
        <a class="navbar-brand" href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index')); ?>">
            <img class="bb-logo" src="/images/logo/logo.svg" width="50" height="50" alt="Blackbox"/></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <div class="go-right">
                <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
                    <div class="welcome">
                        <p>Hallo <?php echo $this->thisUser->getFirstname(); ?></p>
                    </div>
                    <ul class="navbar-nav">
                        <li class="nav-item ">
                            <a href="<?php echo $this->url(array('controller' => 'files', 'action' => 'create')); ?>">
                                <img class="bb-icon" src="/images/icons/upload.svg" width="50" height="50"
                                     alt="Einstellungen"/>
                            </a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <img class="bb-icon" src="/images/icons/settings.svg" width="50" height="50"
                                     alt="Einstellungen"/>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item"
                                   href="<?php echo $this->url(array('controller' => 'user', 'action' => 'index')); ?>">Benutzerdaten
                                    ändern</a>
                                <a class="dropdown-item"
                                   href="<?php echo $this->url(array('controller' => 'user-settings', 'action' => 'index')); ?>">Speichereinstellungen</a>
                                <?php if (Zend_Auth::getInstance()->getStorage()->read()->EMAIL == "cs@christophstockinger.de"): ?>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item"
                                       href="<?php echo $this->url(array('controller' => 'global-settings', 'action' => 'index')); ?>">globale
                                        Einstellungen</a>
                                <?php endif; ?>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'logout')); ?>">
                                <img class="bb-icon" src="/images/icons/logout.svg" width="50" height="50"
                                     alt="Einstellungen"/>
                            </a>
                        </li>

                    </ul>
                <?php else: ?>
                    <a class="btn btn-primary button"
                       href="<?php echo $this->url(array('controller' => 'user', 'action' => 'create')); ?>"
                       role="button">Registrieren</a>
                    <a class="btn btn-primary button"
                       href="<?php echo $this->url(array('controller' => 'user', 'action' => 'login')); ?>"
                       role="button">Anmelden</a>
                <?php endif; ?>
            </div>
        </div>
    </nav>


</header>
<main>
    <div class="page">
        <?php echo $this->layout()->content; ?>
    </div>
</main>

<footer>
    <div class="row footer-content">
        <div class="col-12 col-sm-12 footer-text">
            <p>Uplaod.Taggen.Finden. - Dokumente schneller finden!</p>
            <p>&copy 2018 <a href="http://www.christophstockinger.de">Christoph Stockinger</a></p>
        </div>
    </div>
</footer>
<!--// Javascript & jQuery //-->
<script type="text/javascript" src="/js/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="/js/popper.min.js"></script>
<script type="text/javascript" src="/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/js/func.min.js"></script>
</body>
</html>

<?php

// TODO: Footer programmieren