<?php
$deletesvgicon = '<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 60 60" style="enable-background:new 0 0 60 60;" xml:space="preserve"><g><g id="delete"><path d="M13.3,49.4c0,3.1,2.5,5.6,5.6,5.6h22.2c3.1,0,5.6-2.5,5.6-5.6V16.1H13.3V49.4z M49.4,7.8h-9.7L36.9,5H23.1l-2.8,2.8h-9.7 v5.6h38.9V7.8z"/></g></g></svg>';
$editsvgicon = '<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 60 60" style="enable-background:new 0 0 60 60;" xml:space="preserve"><path d="M54.3,6.9c-1.4-1.4-4.3-0.6-9.1,2.6c-4,2.7-8.9,6.8-13.6,11.6c-7,7-12.4,13.9-14.2,18.2c-0.3-0.1-0.6-0.2-0.9-0.3 c-1.8-0.4-3.8,0.1-5.5,1.3c-2.4,1.7-3,4.1-3.1,4.5c-0.5,1.9-1.4,3.6-2.7,5.1c-0.4,0.5-0.4,1.2,0.1,1.6c1.7,1.5,3.8,2.2,6,2.2 c2.1,0,4.3-0.7,6.3-2.1c0.9-0.6,1.6-1.4,1.7-1.5c1.6-1.8,2.3-4.1,2-6.2c4.2-1.5,11.5-7,18.8-14.4C44.9,24.8,49,20,51.7,16 C54.9,11.2,55.8,8.3,54.3,6.9z"/></svg>';
?>

<div class="content">
    <h2>BlackBox-Settings</h2>

    <h3>Dateiformate</h3>
    <?php
    $fileformats = $this->fileformats;
    ?>

    <div class="row settings">
        <div class="col-12 col-sm-12 col-lg-12 global-data">
            <div class="add">
                <a class="button"
                   href="<?php echo $this->url(array('controller' => 'global-fileformats', 'action' => 'create')); ?>"> Neues Dateiformat
                    anlegen</a>
            </div>
            <table class="fileformat-table" cellpadding="0" cellspacing="0">
                <tr>
                    <th>ID</th>
                    <th>Dateiformat</th>
                    <th>Formatkategorie</th>
                    <th></th>
                </tr>
                <?php
                foreach ($fileformats as $fileformat) {
                    echo "<tr>";
                    echo "<td>" . $fileformat->getFormatid() . "</td>";
                    echo "<td>" . $fileformat->getFileformat() . "</td>";
                    echo "<td>" . $fileformat->getFormatCategorie() . "</td>";
                    echo "<td>";
                    // echo "<a class='button' href='" . $this->url(array('controller' => 'global-fileformats', 'action' => 'edit', 'formatid' => $fileformat->getFormatid())) . "'>$editsvgicon</a>";
                    echo "<a class='button' href='" . $this->url(array('controller' => 'global-fileformats', 'action' => 'delete', 'formatid' => $fileformat->getFormatid())) . "'>$deletesvgicon</a>";

                    echo "</td>";
                    echo "</tr>";
                }
                ?>
            </table>


        </div>
    </div>
</div>


</div>