<div id="view-content">
	<p>View script for controller <b>User</b> and script/action name <b>view</b></p>
</div>

<?php
// the variable/array 'user' is generated and set in the
// controller 'user' and action 'view'
//
// all functions to the model user like 'getId()' and 'getFirstname() are
// functions of the model 'user' in the file 'models\user.php
?>

<?php $user = $this->user; ?>

<div class="page-header">
	<a class="pull-right" href="<?php echo $this->url(array('controller' => 'user', 'action' => 'update', 'id' => $user->getId())); ?>"><button type="button" class="btn btn-default">Bearbeiten</button></a>
	<a class="pull-right" href="<?php echo $this->url(array('controller' => 'user', 'action' => 'delete', 'id' => $user->getId())); ?>"><button type="button" class="btn btn-default">Löschen</button></a>
	<h3>Benutzer</h3>
</div>
<div class="jumbotron">
	<div class="media">
	  <div class="media-left">
		  <img alt="Generic placeholder image" class="media-object" data-src="holder.js/400x300?bg=2a2025">
	  </div>
	  <div class="media-body">
		<h1><?php echo $user->getFirstname() . ' ' . $user->getLastname(); ?></h1>
		<h2>Benutzer ID #<?php echo $user->getId(); ?></h2>
		<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
		<p><a href="mailto:<?php echo $user->getEmail(); ?>"><?php echo $user->getEmail(); ?></a></p>
	  </div>
	</div>	
</div>