<?php
$downloadsvg = '<svg version="1.1" id="Ebene_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 100 80" style="enable-background:new 0 0 100 80;" xml:space="preserve"><rect x="10" y="61.9" class="st0" width="80" height="5"/><polygon class="st0" points="36.2,40.7 50.3,54.8 64.6,40.7 61,37.1 52.9,45.3 52.9,16.5 47.9,16.5 47.9,45.3 39.7,37.1 "/></svg>';
$editsvg = '<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 60 60" style="enable-background:new 0 0 60 60;" xml:space="preserve"><path d="M54.3,6.9c-1.4-1.4-4.3-0.6-9.1,2.6c-4,2.7-8.9,6.8-13.6,11.6c-7,7-12.4,13.9-14.2,18.2c-0.3-0.1-0.6-0.2-0.9-0.3 c-1.8-0.4-3.8,0.1-5.5,1.3c-2.4,1.7-3,4.1-3.1,4.5c-0.5,1.9-1.4,3.6-2.7,5.1c-0.4,0.5-0.4,1.2,0.1,1.6c1.7,1.5,3.8,2.2,6,2.2 c2.1,0,4.3-0.7,6.3-2.1c0.9-0.6,1.6-1.4,1.7-1.5c1.6-1.8,2.3-4.1,2-6.2c4.2-1.5,11.5-7,18.8-14.4C44.9,24.8,49,20,51.7,16 C54.9,11.2,55.8,8.3,54.3,6.9z"/></svg>';


$resultdata = $this->resultdata;
$user = $this->user;
?>

<div class="content no-bg">

    <h1>Blackbox</h1>

    <div class="search">
        <?php
        echo $this->form;

        if ($resultdata == 0 ||(count($resultdata) == 0) ): ?>
            <div class="col-12 col-sm-12 search-results">
                <p>Leider keine Einträge gefunden.</p>
            </div>
        <?php else: ?>
            <div class="col-12 col-sm-12 search-results">
                <ul class="list-unstyled">
                    <?php foreach ($resultdata as $data): ?>
                        <li class="media">
                            <?php
                            switch ($data['fileformat']) {
                                case "PDF":
                                    echo "<img class='mr-3' src='/images/icons/pdf.svg' width='50' height='50' alt='" . $data['fileformat'] . "' />";
                                    break;

                                case "ZIP":
                                case "TAR":
                                    echo "<img class='mr-3' src='/images/icons/zip.svg' width='50' height='50' alt='" . $data['fileformat'] . "' />";
                                    break;

                                case "TXT";
                                    echo "<img class='mr-3' src='/images/icons/txt.svg' width='50' height='50' alt='" . $data['fileformat'] . "' />";
                                    break;

                                case "BMP":
                                case "GIF":
                                case "JPG":
                                case "PNG":
                                    echo "<img class='mr-3' src='../data/" . $data['location'] . "/" . $data['filename'] . "' width='50' height='50' alt='" . $data['fileformat'] . "' />";
                                    break;

                            }
                            ?>
                            <div class="media-body">
                                <h5><?php echo $data['filedisplayname']; ?></h5>
                                <p><strong>Tags:</strong> <?php echo (str_replace(";", " ", $data['filetags'])); ?></p>
                                <div class="buttons">
                                    <a class='download' target='_blank'
                                       href='/data/<?php echo $data['location'] . "/" . $data['filename']; ?>'><?php echo $downloadsvg; ?></a>
                                    <?php if ($user != null): ?>
                                        <a class='edit'
                                           href='<?php echo $this->url(array('controller' => 'files', 'action' => 'edit', 'fileid' => $data['fileid'])); ?>'><?php echo $editsvg; ?></a>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>

        <?php endif; ?>
    </div>
</div>