<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width initial-scale=1.0"/>

    <title>Blackbox // Uplaod.Taggen.Finden.</title>

    <meta name="description" content=""/>
    <meta name="author" content="Christoph Stockinger"/>
    <meta name="publisher" content="Christoph Stockinger"/>
    <meta name="copyright" content="&copy; Christoph Stockinger"/>
    <meta name="version" content="1.0"/>


    <!--// Favicon //-->
    <link rel="apple-touch-icon" sizes="57x57" href="/images/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/images/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/images/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/images/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/images/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/images/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/images/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/images/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/images/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="/images/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/images/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon/favicon-16x16.png">
    <link rel="manifest" href="/images/favicon/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/images/favicon/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <!--// CSS //-->
    <!--// CSS CS Reset //-->
    <link href="/css/cs-reset.css" rel="stylesheet" type="text/css" media="all">
    <!--// CSS Bootstrap Grid //-->
    <link href="/css/bootstrap-grid.min.css" rel="stylesheet" type="text/css" media="all">
    <!--// CSS Main //-->
    <link href="/css/main.css" rel="stylesheet" type="text/css" media="all">

</head>
<body>
<header>
    <div class="row">
        <?php
        if (Zend_Auth::getInstance()->hasIdentity()) {
            ?>
            <div class="col-4 col-sm-4 col-md-3 settings">
                <a id="settings-icon" href="#settings-navi">
                    <img src="/images/icons/settings.svg" alt="Einstellungen" height="50" width="50"/>
                </a>
                <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'logout')); ?>">
                    <img src="/images/icons/logout.svg" alt="Einstellungen"/>
                </a>
                <div id="settings-navi" class="toggle-navigation">
                    <ul>
                        <li>
                            <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'index')); ?>">
                                Benutzerdaten ändern
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url(array('controller' => 'user-settings', 'action' => 'index')); ?>">
                                Speichereinstellungen
                            </a>
                        </li>
                        <?php if (Zend_Auth::getInstance()->getStorage()->read()->EMAIL == "cs@christophstockinger.de") { ?>
                        <li>
                            <a href="<?php echo $this->url(array('controller' => 'global-settings', 'action' => 'index')); ?>">
                                globale Einstellungen
                            </a>
                        </li>
                            <?php } ?>
                    </ul>

                </div>
            </div>
            <?php
        } else {
            ?>
            <div class="col-4 col-sm-4 col-md-3 login">
                <a class="button" href="<?php echo $this->url(array('controller' => 'user', 'action' => 'login')); ?>">
                    Anmelden
                </a>
            </div>
            <?php
        }
        ?>
        <div class="col-4 col-sm-4 col-md-6 brand">
            <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index')); ?>">
                <img src="/images/logo/logo.svg" alt="Blackbox"/>
            </a>
        </div>
        <?php
        if (Zend_Auth::getInstance()->hasIdentity()) {
        ?>
        <div class="col-4 col-sm-4 col-md-3 file-upload">
            <a href="<?php echo $this->url(array('controller' => 'files', 'action' => 'create')); ?>">
                <img src="/images/icons/upload.svg" alt="Einstellungen"/>
            </a>
        </div>
            <?php
            } else {
            ?>
            <div class="col-4 col-sm-4 col-md-3 registry">
                <a class="button" href="<?php echo $this->url(array('controller' => 'user', 'action' => 'create')); ?>">
                    Registrieren
                </a>
            </div>
            <?php
        }
        ?>
    </div>
</header>
<main>
    <div class="page">
        <?php echo $this->layout()->content; ?>
    </div>
</main>

<footer>

</footer>
<!--// Javascript & jQuery //-->
<script type="text/javascript" src="/js/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="/js/func.js"></script>
</body>
</html>