<div class="content">
    <h2>BlackBox-Registrierung</h2>

    <div class="row settings">
        <div class="col-12 col-sm-12 settings-infotext">
            <?php $errormessage = $this->errormessage;

            if (isset($errormessage)) {
                echo "<p class='error'>" . $errormessage . "</p>";
            }
            ?>
        </div>
        <?php echo $this->form; ?>
    </div>
</div>