<div class="content">
    <h2>BlackBox-Settings</h2>

    <h3>Deine persönlichen Account-Daten bearbeiten</h3>


    <div class="row settings">
        <div class="col-12 col-sm-12 abbruch">
            <a class='button' href="<?php echo $this->url(array('controller' => 'user-settings', 'action' => 'index')); ?>">Abbrechen</a>
        </div>
        <?php echo $this->form; ?>
        <div class="col-12 col-sm-12 edit">
            <a href="<?php echo $this->url(array( 'controller' => 'user', 'action' => 'delete' )); ?>" class="button">Account löschen</a>
        </div>
    </div>
</div>
