<div class="content">
    <h2>Black meldet einen aufgetretenen Fehler</h2>

    <h3><?php echo $this->message ?></h3>

    <?php if (isset($this->exception)): ?>

        <h3>Exception Information / Exception information</h3>
        <p>
            <b>Meldung / Message:</b> <?php echo $this->exception->getMessage() ?>
        </p>

        <h3>Stapelverfolgung / Stack trace</h3>
        <p><?php echo $this->exception->getTraceAsString() ?></p>

        <h3>Angeforderte Parameter / Request Parameters</h3>
        <p><?php echo $this->escape(var_export($this->request->getParams(), true)) ?></p>

    <?php endif ?>

</div>
