<div class="content">
    <h2>BlackBox-Settings</h2>

    <h3>Globaale Einstellungen bearbeiten</h3>

    <div class="row settings">
        <div class="col-12 col-sm-12 abbruch">
            <a class='button' href="<?php echo $this->url(array('controller' => 'global-settings', 'action' => 'index')); ?>">Abbrechen</a>
        </div>
        <?php
        if ( isset($this->error) ) {
            echo "<p>" . $this->error . "</p>";
        }

        echo $this->form;
        ?>

    </div>

</div>