<div class="content">
    <h2>BlackBox-Settings</h2>

    <h3>globale Einstellungen</h3>


    <?php
    $globalsettings = $this->globalsettings;
    ?>

    <div class="row settings">
        <div class="col-12 col-sm-12 col-lg-12 global-data">
            <div class="row">
                <?php
                foreach ($globalsettings as $globalsetting) {

                    switch ($globalsetting->getSettingsId()) {
                        case 1:
                        case 2:
                            ?>

                            <div class="col-12 col-sm-12 col-md-2 settings-attribute">
                                <p><?php echo $globalsetting->getSettingsDisplayName(); ?></p></div>
                            <div class="col-12 col-sm-12 col-md-10 settings-value">
                                <p><?php echo ($globalsetting->getSettingsValue() >= 1000) ? (($globalsetting->getSettingsValue() / 1000) . " GB") : ($globalsetting->getSettingsValue() . " MB"); ?></p>
                            </div>
                            <?php
                            break;

                        case 3:
                            ?>

                            <div class="col-12 col-sm-12 col-md-2 settings-attribute">
                                <p><?php echo $globalsetting->getSettingsDisplayName(); ?></p></div>
                            <div class="col-12 col-sm-12 col-md-8 settings-value">
                                <?php
                                $fileformats = explode(";", $globalsetting->getSettingsValue());
                                echo "<ul class='fileformat'>";
                                foreach ($fileformats as $fileformat) {
                                    echo "<li>" . $fileformat . "</li>";
                                }
                                echo "</ul>";
                                ?>
                            </div>
                            <?php
                            break;

                    }

                }
                ?>

                <div class="col-12 col-sm-12 edit">
                    <a href="<?php echo $this->url( array('controller' => 'global-settings', 'action' => 'edit')); ?>" class="button">Bearbeiten</a>
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-12 col-lg-6 user-save-data">

        </div>
    </div>


</div>